#!/usr/bin/python
import sys
import os

COMMANDS = {
	'commands': {
		'put': {
			'commands': {
				'pwd': None,
				'ls': {
					'folders': True,
					'files': True
				},
				'cd': {
					'folders': True
				},
				'transfers': None,
				'add': None,
				'save': {
					'folders': True,
					'files': True
				},
				'rm': {
					'folders': True,
					'files': True
				}
			}
		}
	}
}

DEFAULT = {
	'folders': True,
	'files': True
}

PID = sys.argv[1]
COMP_CWORD = int(sys.argv[2])
COMP_WORDS = sys.argv[3:]

def main():
	current = COMMANDS

	for i in range(COMP_CWORD):
		word = COMP_WORDS[i]
		if 'commands' in current and word in current['commands']:
			current = current['commands'][word]
		else:
			current = DEFAULT
			break

	if current is not None:
		if 'commands' in current:
			for command in current['commands']:
				print command

		file_flag = 'files' in current and current['files']
		folder_flag = 'folders' in current and current['folders']
		if file_flag or folder_flag:
			try:
				f = open(os.path.expanduser('~/.put-cli/autocomplete/' + PID), 'r')
				for line in f:
					name, file_type = line[:-1].split('\t')
					if (file_type == 'FOLDER' and folder_flag) or (file_type != 'FOLDER' and file_flag):
						print name
			except (OSError, IOError):
				pass

if __name__ == '__main__':
	main()
