#!/usr/bin/python
import sys
import os

commands = {
	'commands': {
		'put': {
			'commands': {
				'pwd': None,
				'ls': {
					'folders': True,
					'files': True
				},
				'cd': {
					'folders': True
				},
				'transfers': {
					'commands': {
						'show': None,
						'clear': None
					}
				},
				'add': None,
				'save': {
					'folders': True,
					'files': True
				}
			}
		}
	}
}

pid = sys.argv[1]
comp_cword = int(sys.argv[2])
comp_words = sys.argv[3:]
current = commands

for i in range(comp_cword):
	word = comp_words[i]
	if 'commands' in current and word in current['commands']:
		current = current['commands'][word]
	else:
		sys.exit(0)

if current is not None:
	if 'commands' in current:
		for command in current['commands']:
			print command

	file_flag = 'files' in current and current['files']
	folder_flag = 'folders' in current and current['folders']
	if file_flag or folder_flag:
		try:
			f = open(os.path.expanduser('~/.put-cli/autocomplete/' + pid), 'r')
			for line in f:
				name, file_type = line[:-1].split('\t')
				if (file_type == '0' and folder_flag) or (file_type != '0' and file_flag):
					print name
		except Exception as e:
			pass
